name: Flutter Nightly Build

on:
  schedule:
    # schedule build every Saturday
    - cron: "0 8 1 * *"
  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "nightly"
